import type { GenreId, LanguageId, MoodId, Song } from '../data'

type ConcreteLanguage = Exclude<LanguageId, 'random'>
type ConcreteGenre = Exclude<GenreId, 'random'>
type EmotionalProfile = 'bright' | 'gentle' | 'melancholy' | 'reflective' | 'intense' | 'restless'
type SongSeed = readonly [
  title: string,
  artist: string,
  language: ConcreteLanguage,
  genres: readonly ConcreteGenre[],
  profile: EmotionalProfile,
]

const profileDefaults: Record<
  EmotionalProfile,
  { moods: MoodId[]; energy: number; reason: string }
> = {
  bright: {
    moods: ['happy', 'calm'],
    energy: 0.74,
    reason: '明亮而熟悉的旋律不需要用力，就能让此刻多一点轻盈。',
  },
  gentle: {
    moods: ['calm', 'lonely', 'tired'],
    energy: 0.32,
    reason: '温和的声音留出足够空间，适合让呼吸和思绪慢慢安静下来。',
  },
  melancholy: {
    moods: ['low', 'lonely', 'unclear'],
    energy: 0.36,
    reason: '它不急着解释难过，只让那些没有说完的感受被好好听见。',
  },
  reflective: {
    moods: ['unclear', 'calm', 'tired'],
    energy: 0.45,
    reason: '旋律像一次不被催促的回望，陪你把复杂心绪慢慢理清。',
  },
  intense: {
    moods: ['angry', 'tired', 'anxious'],
    energy: 0.88,
    reason: '有力量的节奏为情绪打开出口，让压在心里的能量得到释放。',
  },
  restless: {
    moods: ['anxious', 'unclear', 'tired'],
    energy: 0.66,
    reason: '流动的节拍接住停不下来的思绪，让混乱逐渐找到自己的秩序。',
  },
}

const languagePalettes: Record<ConcreteLanguage, [string, string]> = {
  mandarin: ['#a58972', '#2e3d48'],
  cantonese: ['#9b806f', '#303746'],
  english: ['#7e98a3', '#293444'],
  french: ['#a07c87', '#343344'],
  japanese: ['#829aa8', '#34364b'],
  korean: ['#95889d', '#2e3b4b'],
  other: ['#8b9d84', '#343e40'],
}

function stableCatalogId(title: string, artist: string, language: ConcreteLanguage) {
  const source = `${language}:${title}:${artist}`
  let hash = 2166136261
  for (let index = 0; index < source.length; index += 1) {
    hash ^= source.charCodeAt(index)
    hash = Math.imul(hash, 16777619)
  }
  return `catalog-${(hash >>> 0).toString(36)}`
}

const expandedSeeds: SongSeed[] = [
  ['月亮代表我的心', '邓丽君', 'mandarin', ['pop', 'classic'], 'gentle'],
  ['甜蜜蜜', '邓丽君', 'mandarin', ['pop', 'classic'], 'bright'],
  ['红豆', '王菲', 'mandarin', ['pop', 'classic'], 'melancholy'],
  ['匆匆那年', '王菲', 'mandarin', ['pop'], 'melancholy'],
  ['青花瓷', '周杰伦', 'mandarin', ['pop', 'classic'], 'gentle'],
  ['晴天', '周杰伦', 'mandarin', ['pop', 'rnb'], 'melancholy'],
  ['七里香', '周杰伦', 'mandarin', ['pop', 'rnb'], 'bright'],
  ['江南', '林俊杰', 'mandarin', ['pop', 'rnb'], 'melancholy'],
  ['修炼爱情', '林俊杰', 'mandarin', ['pop'], 'melancholy'],
  ['勇气', '梁静茹', 'mandarin', ['pop', 'classic'], 'reflective'],
  ['可惜不是你', '梁静茹', 'mandarin', ['pop'], 'melancholy'],
  ['后来', '刘若英', 'mandarin', ['pop', 'classic'], 'melancholy'],
  ['我怀念的', '孙燕姿', 'mandarin', ['pop'], 'melancholy'],
  ['天黑黑', '孙燕姿', 'mandarin', ['folk', 'pop'], 'reflective'],
  ['童话', '光良', 'mandarin', ['pop', 'classic'], 'gentle'],
  ['小幸运', '田馥甄', 'mandarin', ['pop'], 'bright'],
  ['追光者', '岑宁儿', 'mandarin', ['pop'], 'gentle'],
  ['南山南', '马頔', 'mandarin', ['folk'], 'melancholy'],
  ['成都', '赵雷', 'mandarin', ['folk'], 'gentle'],
  ['像我这样的人', '毛不易', 'mandarin', ['folk', 'pop'], 'reflective'],
  ['普通DISCO', '洛天依 & 言和', 'mandarin', ['electronic', 'pop'], 'bright'],
  ['新长征路上的摇滚', '崔健', 'mandarin', ['rock', 'classic'], 'intense'],
  ['一无所有', '崔健', 'mandarin', ['rock', 'classic'], 'intense'],
  ['差不多先生', 'MC HotDog', 'mandarin', ['rap', 'classic'], 'intense'],

  ['红日', '李克勤', 'cantonese', ['pop', 'classic'], 'bright'],
  ['一生不变', '李克勤', 'cantonese', ['pop', 'classic'], 'melancholy'],
  ['月半小夜曲', '李克勤', 'cantonese', ['pop', 'classic'], 'melancholy'],
  ['千千阕歌', '陈慧娴', 'cantonese', ['pop', 'classic'], 'melancholy'],
  ['飘雪', '陈慧娴', 'cantonese', ['pop', 'classic'], 'melancholy'],
  ['容易受伤的女人', '王菲', 'cantonese', ['pop', 'classic'], 'melancholy'],
  ['约定', '王菲', 'cantonese', ['pop', 'classic'], 'gentle'],
  ['少女的祈祷', '杨千嬅', 'cantonese', ['pop'], 'gentle'],
  ['可惜我是水瓶座', '杨千嬅', 'cantonese', ['pop'], 'melancholy'],
  ['再见二丁目', '杨千嬅', 'cantonese', ['pop'], 'melancholy'],
  ['K歌之王', '陈奕迅', 'cantonese', ['pop', 'classic'], 'melancholy'],
  ['最佳损友', '陈奕迅', 'cantonese', ['pop'], 'melancholy'],
  ['陀飞轮', '陈奕迅', 'cantonese', ['pop', 'classic'], 'reflective'],
  ['葡萄成熟时', '陈奕迅', 'cantonese', ['pop'], 'reflective'],
  ['浮夸', '陈奕迅', 'cantonese', ['pop'], 'intense'],
  ['一生所爱', '卢冠廷', 'cantonese', ['folk', 'classic'], 'melancholy'],
  ['似是故人来', '梅艳芳', 'cantonese', ['pop', 'classic'], 'reflective'],
  ['夕阳之歌', '梅艳芳', 'cantonese', ['pop', 'classic'], 'melancholy'],
  ['沉默是金', '张国荣 & 许冠杰', 'cantonese', ['pop', 'classic'], 'reflective'],
  ['风继续吹', '张国荣', 'cantonese', ['pop', 'classic'], 'melancholy'],
  ['谁伴我闯荡', 'Beyond', 'cantonese', ['rock', 'classic'], 'reflective'],
  ['喜欢你', 'Beyond', 'cantonese', ['rock', 'classic'], 'bright'],
  ['冷雨夜', 'Beyond', 'cantonese', ['rock', 'classic'], 'melancholy'],
  ['大懒堂', 'LMF', 'cantonese', ['rap', 'electronic'], 'intense'],

  ['Bohemian Rhapsody', 'Queen', 'english', ['rock', 'classic'], 'intense'],
  ["Don't Stop Me Now", 'Queen', 'english', ['rock', 'classic'], 'bright'],
  ['Hotel California', 'Eagles', 'english', ['rock', 'classic'], 'reflective'],
  ['Dreams', 'Fleetwood Mac', 'english', ['pop', 'rock', 'classic'], 'gentle'],
  ['Go Your Own Way', 'Fleetwood Mac', 'english', ['rock', 'classic'], 'intense'],
  ['Imagine', 'John Lennon', 'english', ['pop', 'classic'], 'gentle'],
  ['Let It Be', 'The Beatles', 'english', ['pop', 'classic'], 'gentle'],
  ['Here Comes the Sun', 'The Beatles', 'english', ['pop', 'classic'], 'bright'],
  ['Billie Jean', 'Michael Jackson', 'english', ['pop', 'rnb', 'classic'], 'restless'],
  ['Man in the Mirror', 'Michael Jackson', 'english', ['pop', 'rnb', 'classic'], 'reflective'],
  ['Rolling in the Deep', 'Adele', 'english', ['pop', 'blues'], 'intense'],
  ['Someone Like You', 'Adele', 'english', ['pop', 'classic'], 'melancholy'],
  ['Blinding Lights', 'The Weeknd', 'english', ['pop', 'electronic', 'rnb'], 'bright'],
  ['Save Your Tears', 'The Weeknd', 'english', ['pop', 'electronic', 'rnb'], 'melancholy'],
  ['Shape of You', 'Ed Sheeran', 'english', ['pop'], 'bright'],
  ['Perfect', 'Ed Sheeran', 'english', ['pop'], 'gentle'],
  ['Smells Like Teen Spirit', 'Nirvana', 'english', ['rock', 'classic'], 'intense'],
  ['Creep', 'Radiohead', 'english', ['rock', 'classic'], 'melancholy'],
  ['Take Me Home, Country Roads', 'John Denver', 'english', ['folk', 'classic'], 'gentle'],
  ['Hallelujah', 'Leonard Cohen', 'english', ['folk', 'classic'], 'reflective'],
  ['Numb', 'Linkin Park', 'english', ['rock'], 'intense'],
  ['Stan', 'Eminem', 'english', ['rap', 'classic'], 'restless'],
  ['Juicy', 'The Notorious B.I.G.', 'english', ['rap', 'classic'], 'bright'],
  ['Lean on Me', 'Bill Withers', 'english', ['rnb', 'classic'], 'gentle'],

  ['La Mer', 'Charles Trenet', 'french', ['pop', 'classic'], 'gentle'],
  ['Les Champs-Élysées', 'Joe Dassin', 'french', ['pop', 'classic'], 'bright'],
  ['Non, je ne regrette rien', 'Édith Piaf', 'french', ['pop', 'classic'], 'intense'],
  ['Padam, padam...', 'Édith Piaf', 'french', ['pop', 'classic'], 'restless'],
  ['Tous les garçons et les filles', 'Françoise Hardy', 'french', ['pop', 'classic'], 'melancholy'],
  ['Comment te dire adieu', 'Françoise Hardy', 'french', ['pop', 'classic'], 'reflective'],
  ['Joe le taxi', 'Vanessa Paradis', 'french', ['pop', 'classic'], 'bright'],
  ['Moi... Lolita', 'Alizée', 'french', ['pop', 'electronic'], 'bright'],
  ['Je veux', 'Zaz', 'french', ['pop', 'blues'], 'bright'],
  ['On ira', 'Zaz', 'french', ['pop', 'folk'], 'bright'],
  ['Tous les mêmes', 'Stromae', 'french', ['pop', 'electronic'], 'restless'],
  ['Papaoutai', 'Stromae', 'french', ['pop', 'electronic'], 'reflective'],
  ['Balance ton quoi', 'Angèle', 'french', ['pop', 'electronic'], 'bright'],
  ['Tout oublier', 'Angèle & Roméo Elvis', 'french', ['pop', 'rap'], 'bright'],
  ['Tourner dans le vide', 'Indila', 'french', ['pop'], 'melancholy'],
  ['La grenade', 'Clara Luciani', 'french', ['pop', 'rock'], 'intense'],
  ['Respire encore', 'Clara Luciani', 'french', ['pop', 'electronic'], 'bright'],
  ["Quelqu'un m'a dit", 'Carla Bruni', 'french', ['folk', 'pop'], 'gentle'],
  ['Je te promets', 'Johnny Hallyday', 'french', ['rock', 'classic'], 'reflective'],
  ["J't'emmène au vent", 'Louise Attaque', 'french', ['rock', 'folk'], 'bright'],
  ["L'aventurier", 'Indochine', 'french', ['rock', 'classic'], 'intense'],
  ['Cendrillon', 'Téléphone', 'french', ['rock', 'classic'], 'reflective'],
  ['Djadja', 'Aya Nakamura', 'french', ['pop', 'rnb'], 'restless'],
  ['La même', 'GIMS & Vianney', 'french', ['pop', 'rap'], 'bright'],

  ['上を向いて歩こう', '坂本九', 'japanese', ['pop', 'classic'], 'gentle'],
  ['クリスマス・イブ', '山下達郎', 'japanese', ['pop', 'classic'], 'melancholy'],
  ['RIDE ON TIME', '山下達郎', 'japanese', ['pop', 'rnb', 'classic'], 'bright'],
  ['Automatic', '宇多田ヒカル', 'japanese', ['pop', 'rnb', 'classic'], 'restless'],
  ['Flavor Of Life', '宇多田ヒカル', 'japanese', ['pop'], 'melancholy'],
  ['Pretender', 'Official髭男dism', 'japanese', ['pop'], 'melancholy'],
  ['Subtitle', 'Official髭男dism', 'japanese', ['pop'], 'reflective'],
  ['夜に駆ける', 'YOASOBI', 'japanese', ['pop', 'electronic'], 'restless'],
  ['アイドル', 'YOASOBI', 'japanese', ['pop', 'electronic'], 'intense'],
  ['群青', 'YOASOBI', 'japanese', ['pop'], 'bright'],
  ['紅蓮華', 'LiSA', 'japanese', ['rock', 'pop'], 'intense'],
  ['残酷な天使のテーゼ', '高橋洋子', 'japanese', ['pop', 'classic'], 'intense'],
  ['魂のルフラン', '高橋洋子', 'japanese', ['pop', 'classic'], 'reflective'],
  ['世界が終るまでは…', 'WANDS', 'japanese', ['rock', 'classic'], 'intense'],
  ['そばかす', 'JUDY AND MARY', 'japanese', ['rock', 'pop', 'classic'], 'bright'],
  ['リライト', 'ASIAN KUNG-FU GENERATION', 'japanese', ['rock'], 'intense'],
  ['チェリー', 'スピッツ', 'japanese', ['rock', 'pop'], 'bright'],
  ['ロビンソン', 'スピッツ', 'japanese', ['rock', 'pop'], 'reflective'],
  ['366日', 'HY', 'japanese', ['pop'], 'melancholy'],
  ['マリーゴールド', 'あいみょん', 'japanese', ['folk', 'pop'], 'gentle'],
  ['ドライフラワー', '優里', 'japanese', ['folk', 'pop'], 'melancholy'],
  ['踊り子', 'Vaundy', 'japanese', ['pop', 'electronic'], 'restless'],
  ['怪獣の花唄', 'Vaundy', 'japanese', ['rock', 'pop'], 'bright'],
  ['NIGHT DANCER', 'imase', 'japanese', ['pop', 'electronic'], 'bright'],

  ['Gangnam Style', 'PSY', 'korean', ['pop', 'electronic', 'rap'], 'bright'],
  ['Dynamite', 'BTS', 'korean', ['pop'], 'bright'],
  ['Butter', 'BTS', 'korean', ['pop', 'rnb'], 'bright'],
  ['FAKE LOVE', 'BTS', 'korean', ['pop'], 'melancholy'],
  ['Boy With Luv', 'BTS feat. Halsey', 'korean', ['pop'], 'bright'],
  ['DDU-DU DDU-DU', 'BLACKPINK', 'korean', ['pop', 'rap'], 'intense'],
  ['Kill This Love', 'BLACKPINK', 'korean', ['pop', 'rap'], 'intense'],
  ['How You Like That', 'BLACKPINK', 'korean', ['pop', 'rap'], 'intense'],
  ['Gee', "Girls' Generation", 'korean', ['pop', 'classic'], 'bright'],
  ['Into the New World', "Girls' Generation", 'korean', ['pop', 'classic'], 'bright'],
  ['Nobody', 'Wonder Girls', 'korean', ['pop', 'classic'], 'bright'],
  ['Tell Me', 'Wonder Girls', 'korean', ['pop', 'classic'], 'bright'],
  ['Fantastic Baby', 'BIGBANG', 'korean', ['pop', 'electronic', 'rap'], 'intense'],
  ['BANG BANG BANG', 'BIGBANG', 'korean', ['pop', 'electronic', 'rap'], 'intense'],
  ['Eyes, Nose, Lips', 'TAEYANG', 'korean', ['rnb', 'pop'], 'melancholy'],
  ['LOVE SCENARIO', 'iKON', 'korean', ['pop', 'rap'], 'reflective'],
  ['Palette', 'IU feat. G-DRAGON', 'korean', ['pop', 'rnb'], 'reflective'],
  ['Good Day', 'IU', 'korean', ['pop', 'classic'], 'bright'],
  ['Hype Boy', 'NewJeans', 'korean', ['pop', 'rnb'], 'bright'],
  ['Super Shy', 'NewJeans', 'korean', ['pop', 'electronic'], 'bright'],
  ['Psycho', 'Red Velvet', 'korean', ['pop', 'rnb'], 'restless'],
  ['LOVE DIVE', 'IVE', 'korean', ['pop', 'electronic'], 'restless'],
  ['Next Level', 'aespa', 'korean', ['pop', 'electronic'], 'intense'],
  ['Replay', 'SHINee', 'korean', ['rnb', 'pop', 'classic'], 'bright'],

  ['Despacito', 'Luis Fonsi feat. Daddy Yankee', 'other', ['pop', 'rnb'], 'bright'],
  ['Bailando', 'Enrique Iglesias', 'other', ['pop'], 'bright'],
  ['La Camisa Negra', 'Juanes', 'other', ['rock', 'pop'], 'bright'],
  ['Me Gustas Tú', 'Manu Chao', 'other', ['folk', 'pop'], 'bright'],
  ['Vivir Mi Vida', 'Marc Anthony', 'other', ['pop'], 'bright'],
  ['Gasolina', 'Daddy Yankee', 'other', ['rap', 'electronic'], 'intense'],
  ['Corazón Espinado', 'Santana feat. Maná', 'other', ['rock', 'blues'], 'intense'],
  ['Bésame Mucho', 'Cesária Évora', 'other', ['classic', 'blues'], 'gentle'],
  ['Garota de Ipanema', 'João Gilberto', 'other', ['classic', 'light'], 'gentle'],
  ['Chega de Saudade', 'João Gilberto', 'other', ['classic', 'light'], 'reflective'],
  ['Mas que Nada', 'Sérgio Mendes', 'other', ['pop', 'classic'], 'bright'],
  ['Ai Se Eu Te Pego', 'Michel Teló', 'other', ['pop'], 'bright'],
  ['Con te partirò', 'Andrea Bocelli', 'other', ['classic', 'pop'], 'reflective'],
  ['Azzurro', 'Adriano Celentano', 'other', ['pop', 'classic'], 'bright'],
  ['Sarà perché ti amo', 'Ricchi e Poveri', 'other', ['pop', 'classic'], 'bright'],
  ['Bella ciao', 'Manu Pilas', 'other', ['folk', 'classic'], 'intense'],
  ['Major Tom (völlig losgelöst)', 'Peter Schilling', 'other', ['electronic', 'classic'], 'restless'],
  ['Du hast', 'Rammstein', 'other', ['rock', 'electronic'], 'intense'],
  ['Sonne', 'Rammstein', 'other', ['rock'], 'intense'],
  ['Dragostea Din Tei', 'O-Zone', 'other', ['pop', 'electronic'], 'bright'],
  ['Svefn-g-englar', 'Sigur Rós', 'other', ['rock', 'light'], 'gentle'],
  ['La solitudine', 'Laura Pausini', 'other', ['pop', 'classic'], 'melancholy'],
  ['Mutter', 'Rammstein', 'other', ['rock'], 'melancholy'],
  ['Chan Chan', 'Buena Vista Social Club', 'other', ['folk', 'classic'], 'gentle'],
]

export const expandedSongs: Song[] = expandedSeeds.map(
  ([title, artist, language, genres, profile]) => {
    const defaults = profileDefaults[profile]
    return {
      id: stableCatalogId(title, artist, language),
      title,
      artist,
      language,
      genres: [...genres],
      moods: [...defaults.moods],
      energy: defaults.energy,
      reason: defaults.reason,
      accent: languagePalettes[language],
    }
  },
)
