import { expandedSongs } from './catalog/expanded'
import { validateCatalog } from './catalog/validation'

export type MoodId =
  | 'happy'
  | 'calm'
  | 'low'
  | 'lonely'
  | 'anxious'
  | 'tired'
  | 'angry'
  | 'unclear'

export type LanguageId =
  | 'mandarin'
  | 'cantonese'
  | 'english'
  | 'french'
  | 'japanese'
  | 'korean'
  | 'other'
  | 'random'

export type GenreId =
  | 'pop'
  | 'rock'
  | 'rnb'
  | 'folk'
  | 'blues'
  | 'classic'
  | 'light'
  | 'electronic'
  | 'rap'
  | 'random'

export interface Song {
  id: string
  title: string
  artist: string
  language: Exclude<LanguageId, 'random'>
  genres: Exclude<GenreId, 'random'>[]
  moods: MoodId[]
  energy: number
  reason: string
  accent: [string, string]
}

export const moodOptions = [
  { id: 'happy' as const, label: '开心', hint: '想把此刻的明亮延长一点', symbol: '✦' },
  { id: 'calm' as const, label: '平静', hint: '世界刚好安静，呼吸也很轻', symbol: '≈' },
  { id: 'low' as const, label: '低落', hint: '不急着振作，只想被理解', symbol: '↓' },
  { id: 'lonely' as const, label: '孤独', hint: '想让一个声音陪在身边', symbol: '○' },
  { id: 'anxious' as const, label: '焦虑', hint: '思绪很多，想慢慢停下来', symbol: '∿' },
  { id: 'tired' as const, label: '疲惫', hint: '今天已经做得足够多了', symbol: '—' },
  { id: 'angry' as const, label: '愤怒', hint: '情绪需要出口，也需要空间', symbol: '↯' },
  { id: 'unclear' as const, label: '说不清', hint: '不必定义，模糊也没有关系', symbol: '…' },
]

export const languageOptions = [
  { id: 'mandarin' as const, label: '普通话', hint: '熟悉的字句' },
  { id: 'cantonese' as const, label: '粤语', hint: '温柔而有余韵' },
  { id: 'english' as const, label: '英语', hint: '辽阔的声音质感' },
  { id: 'french' as const, label: '法语', hint: '浪漫而富有诗意' },
  { id: 'japanese' as const, label: '日语', hint: '细腻的情绪流动' },
  { id: 'korean' as const, label: '韩语', hint: '克制与柔软' },
  { id: 'other' as const, label: '其他', hint: '让耳朵去远方' },
  { id: 'random' as const, label: '随机', hint: '把选择交给此刻' },
]

export const genreOptions = [
  { id: 'pop' as const, label: '流行', hint: '容易靠近的旋律' },
  { id: 'rock' as const, label: '摇滚', hint: '让情绪有一点重量' },
  { id: 'rnb' as const, label: 'R&B', hint: '松弛、流动、有温度' },
  { id: 'folk' as const, label: '民谣', hint: '像有人慢慢讲故事' },
  { id: 'blues' as const, label: '蓝调', hint: '与不完美和平相处' },
  { id: 'classic' as const, label: '经典', hint: '时间留下的声音' },
  { id: 'light' as const, label: '轻音乐', hint: '把语言暂时放下' },
  { id: 'electronic' as const, label: '电子', hint: '进入另一层空间' },
  { id: 'rap' as const, label: '说唱', hint: '让表达直接发生' },
  { id: 'random' as const, label: '随机', hint: '不设边界地遇见' },
]

export const moodCopy: Record<MoodId, { title: string; text: string }> = {
  happy: {
    title: '让快乐多停留一会儿。',
    text: '不用克制今天的明亮，喜欢这一刻，本身就是值得庆祝的事。',
  },
  calm: {
    title: '安静不是空白。',
    text: '此刻没有什么需要解决，就让呼吸与旋律自然地经过你。',
  },
  low: {
    title: '今天不必急着变好。',
    text: '先允许自己安静一会儿。低落不需要答案，它也值得被温柔地接住。',
  },
  lonely: {
    title: '有人与你听见同一种夜色。',
    text: '孤独不是被世界遗忘，只是此刻需要一个声音，轻轻坐在你身边。',
  },
  anxious: {
    title: '先把世界调慢一点。',
    text: '不用一次想完所有事情。跟着这一首歌，只照顾接下来的几分钟。',
  },
  tired: {
    title: '今天已经做得足够多了。',
    text: '现在可以把肩膀放下来。休息不是停滞，而是身体在认真保护你。',
  },
  angry: {
    title: '你的愤怒有它的来处。',
    text: '不必马上原谅，也不用压低声音。先让情绪拥有安全的出口。',
  },
  unclear: {
    title: '说不清，也是一种真实。',
    text: '你不必立刻为感受命名。让这首歌陪你待在模糊里，慢慢看见自己。',
  },
}

const curatedSongs: Song[] = [
  {
    id: 'sunset-infinite',
    title: '夕阳无限好',
    artist: '陈奕迅',
    language: 'cantonese',
    genres: ['pop', 'classic'],
    moods: ['low', 'calm', 'tired'],
    energy: 0.36,
    reason: '克制而温柔，不急着让你振作，只是陪你慢慢消化此刻。',
    accent: ['#d59468', '#2b3e53'],
  },
  {
    id: 'spring-summer-autumn-winter',
    title: '春夏秋冬',
    artist: '张国荣',
    language: 'cantonese',
    genres: ['pop', 'classic'],
    moods: ['lonely', 'calm', 'unclear'],
    energy: 0.3,
    reason: '像一封没有催促的信，用熟悉的温度陪你穿过四季。',
    accent: ['#b69378', '#3c3146'],
  },
  {
    id: 'boundless-oceans',
    title: '海阔天空',
    artist: 'Beyond',
    language: 'cantonese',
    genres: ['rock', 'classic'],
    moods: ['angry', 'tired', 'low'],
    energy: 0.82,
    reason: '它不否认现实的重量，却给情绪留出了一片足够辽阔的天空。',
    accent: ['#748fa6', '#161c2b'],
  },
  {
    id: 'tenderness',
    title: '温柔',
    artist: '五月天',
    language: 'mandarin',
    genres: ['pop', 'rock'],
    moods: ['low', 'lonely', 'unclear'],
    energy: 0.52,
    reason: '熟悉的旋律不会追问发生了什么，只把温柔留在你身边。',
    accent: ['#9f7b77', '#27384d'],
  },
  {
    id: 'the-ordinary-road',
    title: '平凡之路',
    artist: '朴树',
    language: 'mandarin',
    genres: ['folk', 'rock'],
    moods: ['tired', 'unclear', 'calm'],
    energy: 0.6,
    reason: '它承认迷惘，也承认继续走下去不需要轰轰烈烈。',
    accent: ['#9d8865', '#273126'],
  },
  {
    id: 'encounter',
    title: '遇见',
    artist: '孙燕姿',
    language: 'mandarin',
    genres: ['pop', 'classic'],
    moods: ['lonely', 'calm', 'low'],
    energy: 0.4,
    reason: '轻盈的旋律给等待留出余地，也让孤单显得不再那么漫长。',
    accent: ['#96a8ab', '#393340'],
  },
  {
    id: 'the-name-engraved',
    title: '刻在我心底的名字',
    artist: '卢广仲',
    language: 'mandarin',
    genres: ['pop'],
    moods: ['lonely', 'low', 'unclear'],
    energy: 0.34,
    reason: '有些想念不必被解释，旋律会替你保存那些没有说完的话。',
    accent: ['#8e777e', '#243346'],
  },
  {
    id: 'yellow',
    title: 'Yellow',
    artist: 'Coldplay',
    language: 'english',
    genres: ['pop', 'rock'],
    moods: ['lonely', 'calm', 'happy'],
    energy: 0.56,
    reason: '温暖的吉他像远处亮起的灯，让此刻拥有可以靠近的方向。',
    accent: ['#c0aa63', '#243342'],
  },
  {
    id: 'no-surprises',
    title: 'No Surprises',
    artist: 'Radiohead',
    language: 'english',
    genres: ['rock', 'classic'],
    moods: ['tired', 'low', 'anxious'],
    energy: 0.28,
    reason: '清澈又疏离的声音，为疲惫保留了一处不被打扰的空间。',
    accent: ['#7d9ba0', '#2b2c35'],
  },
  {
    id: 'lovely-day',
    title: 'Lovely Day',
    artist: 'Bill Withers',
    language: 'english',
    genres: ['rnb', 'classic'],
    moods: ['happy', 'calm'],
    energy: 0.72,
    reason: '松弛的律动不会用力过猛，只自然地把好心情往前推一点。',
    accent: ['#c18a55', '#435d56'],
  },
  {
    id: 'dont-know-why',
    title: "Don't Know Why",
    artist: 'Norah Jones',
    language: 'english',
    genres: ['blues', 'rnb'],
    moods: ['calm', 'low', 'unclear'],
    energy: 0.24,
    reason: '柔和的人声不急着厘清缘由，适合陪伴那些难以命名的感受。',
    accent: ['#977f6f', '#2e3842'],
  },
  {
    id: 'la-vie-en-rose',
    title: 'La Vie en rose',
    artist: 'Édith Piaf',
    language: 'french',
    genres: ['classic', 'pop'],
    moods: ['happy', 'calm', 'lonely'],
    energy: 0.42,
    reason: '温暖而笃定的歌声像一束旧时光，让柔软的情绪被轻轻照亮。',
    accent: ['#b8878e', '#3b3040'],
  },
  {
    id: 'je-te-laisserai-des-mots',
    title: 'Je te laisserai des mots',
    artist: 'Patrick Watson',
    language: 'french',
    genres: ['light', 'pop'],
    moods: ['low', 'lonely', 'calm', 'tired'],
    energy: 0.2,
    reason: '极轻的钢琴与低语为情绪留出空白，像一句不打扰的陪伴。',
    accent: ['#9b9184', '#29343f'],
  },
  {
    id: 'derniere-danse',
    title: 'Dernière danse',
    artist: 'Indila',
    language: 'french',
    genres: ['pop'],
    moods: ['low', 'lonely', 'anxious', 'unclear'],
    energy: 0.62,
    reason: '旋律让压在心里的感受缓缓流动，不必解释也能得到完整表达。',
    accent: ['#7f819f', '#242b40'],
  },
  {
    id: 'alors-on-danse',
    title: 'Alors on danse',
    artist: 'Stromae',
    language: 'french',
    genres: ['electronic', 'pop'],
    moods: ['angry', 'tired', 'happy', 'unclear'],
    energy: 0.82,
    reason: '克制的电子节拍给复杂情绪一个出口，让身体先替思绪松开一点。',
    accent: ['#92785f', '#252d36'],
  },
  {
    id: 'first-love',
    title: 'First Love',
    artist: '宇多田光',
    language: 'japanese',
    genres: ['pop', 'classic'],
    moods: ['lonely', 'low', 'calm'],
    energy: 0.38,
    reason: '细腻而坦白，让回忆可以被看见，却不要求你回到过去。',
    accent: ['#a57d85', '#2c3649'],
  },
  {
    id: 'sparkle',
    title: 'スパークル',
    artist: 'RADWIMPS',
    language: 'japanese',
    genres: ['rock', 'pop'],
    moods: ['happy', 'unclear', 'tired'],
    energy: 0.8,
    reason: '从安静到辽阔，像情绪终于找到了可以奔跑的天际线。',
    accent: ['#6f9fb0', '#3c3158'],
  },
  {
    id: 'one-summers-day',
    title: "One Summer's Day",
    artist: '久石让',
    language: 'japanese',
    genres: ['light', 'classic'],
    moods: ['calm', 'tired', 'anxious'],
    energy: 0.22,
    reason: '钢琴把思绪轻轻放远，让你暂时不必借助语言照顾自己。',
    accent: ['#8ba6a0', '#3c4651'],
  },
  {
    id: 'through-the-night',
    title: 'Through the Night',
    artist: 'IU',
    language: 'korean',
    genres: ['pop', 'light'],
    moods: ['lonely', 'calm', 'low'],
    energy: 0.26,
    reason: '像深夜里压低声音的一句问候，轻轻陪伴而不过分靠近。',
    accent: ['#a39a83', '#2c3c45'],
  },
  {
    id: 'spring-day',
    title: 'Spring Day',
    artist: 'BTS',
    language: 'korean',
    genres: ['pop'],
    moods: ['lonely', 'low', 'tired'],
    energy: 0.58,
    reason: '想念与希望同时存在，让寒冷的情绪里保留一点春天的可能。',
    accent: ['#9f8795', '#294153'],
  },
  {
    id: 'you-were-beautiful',
    title: 'You Were Beautiful',
    artist: 'DAY6',
    language: 'korean',
    genres: ['rock', 'pop'],
    moods: ['low', 'lonely', 'angry'],
    energy: 0.7,
    reason: '把无法回避的情绪交给乐队声响，让遗憾得到一次完整的表达。',
    accent: ['#a3746f', '#24384a'],
  },
  {
    id: 'nuvole-bianche',
    title: 'Nuvole Bianche',
    artist: 'Ludovico Einaudi',
    language: 'other',
    genres: ['light', 'classic'],
    moods: ['anxious', 'low', 'calm', 'unclear'],
    energy: 0.32,
    reason: '反复展开的钢琴声像呼吸，允许复杂情绪一点点沉淀下来。',
    accent: ['#889697', '#303843'],
  },
  {
    id: 'hopipolla',
    title: 'Hoppípolla',
    artist: 'Sigur Rós',
    language: 'other',
    genres: ['light', 'rock'],
    moods: ['happy', 'unclear', 'tired'],
    energy: 0.68,
    reason: '无需听懂每个字，也能感到某种纯粹的生命力从远处靠近。',
    accent: ['#8db1ad', '#4f4662'],
  },
  {
    id: 'weightless',
    title: 'Weightless',
    artist: 'Marconi Union',
    language: 'other',
    genres: ['electronic', 'light'],
    moods: ['anxious', 'tired', 'calm'],
    energy: 0.16,
    reason: '缓慢而连续的声场给焦虑留出距离，让注意力重新回到呼吸。',
    accent: ['#6e9996', '#202d39'],
  },
  {
    id: 'fuji-mountain',
    title: '富士山下',
    artist: '陈奕迅',
    language: 'cantonese',
    genres: ['pop', 'classic'],
    moods: ['low', 'lonely', 'calm'],
    energy: 0.36,
    reason: '它不催促你放下，只把告别写得平静，让执着慢慢找到出口。',
    accent: ['#8b99a5', '#2d3444'],
  },
  {
    id: 'wedding-card-street',
    title: '喜帖街',
    artist: '谢安琪',
    language: 'cantonese',
    genres: ['pop', 'classic'],
    moods: ['low', 'lonely', 'unclear'],
    energy: 0.42,
    reason: '在旧事与告别之间，它替那些舍不得的心情保留一份体面。',
    accent: ['#a48979', '#34313d'],
  },
  {
    id: 'years-like-song',
    title: '岁月如歌',
    artist: '陈奕迅',
    language: 'cantonese',
    genres: ['pop', 'classic'],
    moods: ['tired', 'calm', 'low'],
    energy: 0.44,
    reason: '旋律像回望走过的路，承认疲惫，也珍惜仍在身边的温度。',
    accent: ['#899b9d', '#324044'],
  },
  {
    id: 'glorious-years',
    title: '光辉岁月',
    artist: 'Beyond',
    language: 'cantonese',
    genres: ['rock', 'classic'],
    moods: ['angry', 'tired', 'happy'],
    energy: 0.86,
    reason: '坚定的鼓点和吉他把情绪托起，让不甘重新变成向前的力量。',
    accent: ['#b18c59', '#27313f'],
  },
  {
    id: 'everywhere-kiss',
    title: '处处吻',
    artist: '杨千嬅',
    language: 'cantonese',
    genres: ['pop'],
    moods: ['happy', 'unclear', 'calm'],
    energy: 0.7,
    reason: '轻巧又带一点锋芒，让好心情不必过分认真也能自在流动。',
    accent: ['#b67d84', '#3b3046'],
  },
  {
    id: 'rice-field',
    title: '稻香',
    artist: '周杰伦',
    language: 'mandarin',
    genres: ['pop', 'rnb'],
    moods: ['happy', 'tired', 'calm'],
    energy: 0.68,
    reason: '熟悉的节奏把注意力带回简单日常，提醒你仍有值得靠近的微小快乐。',
    accent: ['#b09a62', '#384637'],
  },
  {
    id: 'simple-love',
    title: '爱很简单',
    artist: '陶喆',
    language: 'mandarin',
    genres: ['rnb', 'pop'],
    moods: ['happy', 'calm', 'lonely'],
    energy: 0.5,
    reason: '松弛的人声与节奏不做复杂解释，只让真诚自然地停在耳边。',
    accent: ['#a98172', '#303c47'],
  },
  {
    id: 'brightest-star-night',
    title: '夜空中最亮的星',
    artist: '逃跑计划',
    language: 'mandarin',
    genres: ['rock', 'pop'],
    moods: ['anxious', 'tired', 'unclear'],
    energy: 0.74,
    reason: '在迷惘里保留一束可追随的光，让没有答案的路也能继续走下去。',
    accent: ['#718ca4', '#202940'],
  },
  {
    id: 'no-need-to-guess',
    title: '不用去猜',
    artist: 'Jony J',
    language: 'mandarin',
    genres: ['rap', 'rnb'],
    moods: ['unclear', 'tired', 'calm'],
    energy: 0.58,
    reason: '直接但不喧闹的表达，适合把绕在心里的念头一层层理开。',
    accent: ['#857d70', '#262d35'],
  },
  {
    id: 'fix-you',
    title: 'Fix You',
    artist: 'Coldplay',
    language: 'english',
    genres: ['rock', 'pop'],
    moods: ['low', 'tired', 'anxious'],
    energy: 0.58,
    reason: '从微光到铺展开来的声浪，它不否认低谷，只在远处留下一盏灯。',
    accent: ['#6f8f9f', '#222c41'],
  },
  {
    id: 'fast-car',
    title: 'Fast Car',
    artist: 'Tracy Chapman',
    language: 'english',
    genres: ['folk', 'classic'],
    moods: ['tired', 'unclear', 'calm'],
    energy: 0.46,
    reason: '平稳的吉他像一条向前延伸的公路，陪你看见疲惫之外的可能。',
    accent: ['#96795d', '#2c3638'],
  },
  {
    id: 'aint-no-sunshine',
    title: "Ain't No Sunshine",
    artist: 'Bill Withers',
    language: 'english',
    genres: ['blues', 'rnb', 'classic'],
    moods: ['lonely', 'low', 'unclear'],
    energy: 0.38,
    reason: '简洁而深沉的声音让想念显出轮廓，却不给你的感受增加负担。',
    accent: ['#9c805f', '#282c32'],
  },
  {
    id: 'lose-yourself',
    title: 'Lose Yourself',
    artist: 'Eminem',
    language: 'english',
    genres: ['rap', 'classic'],
    moods: ['angry', 'tired', 'anxious'],
    energy: 0.94,
    reason: '紧凑的节奏为压力找到出口，把犹豫暂时交给更坚定的步伐。',
    accent: ['#8a8175', '#202327'],
  },
  {
    id: 'ne-me-quitte-pas',
    title: 'Ne me quitte pas',
    artist: 'Jacques Brel',
    language: 'french',
    genres: ['classic', 'pop'],
    moods: ['low', 'lonely', 'unclear'],
    energy: 0.28,
    reason: '近乎坦白的歌声接住舍不得与无能为力，让脆弱拥有被听见的时刻。',
    accent: ['#9b7b6f', '#352e36'],
  },
  {
    id: 'formidable',
    title: 'Formidable',
    artist: 'Stromae',
    language: 'french',
    genres: ['pop', 'electronic'],
    moods: ['low', 'lonely', 'unclear'],
    energy: 0.58,
    reason: '摇晃的节拍与坦率的脆弱并存，让失序的情绪得到诚实表达。',
    accent: ['#8d776c', '#293038'],
  },
  {
    id: 'la-boheme',
    title: 'La Bohème',
    artist: 'Charles Aznavour',
    language: 'french',
    genres: ['classic', 'pop'],
    moods: ['calm', 'low', 'tired'],
    energy: 0.34,
    reason: '旧日巴黎般的旋律缓缓展开，让回忆有温度，也有可以安放的距离。',
    accent: ['#ad8a69', '#3a3333'],
  },
  {
    id: 'basique',
    title: 'Basique',
    artist: 'Orelsan',
    language: 'french',
    genres: ['rap', 'electronic'],
    moods: ['angry', 'unclear', 'tired'],
    energy: 0.76,
    reason: '冷静而清晰的节拍把复杂问题说得直接，为混乱腾出一点秩序。',
    accent: ['#858982', '#242b2f'],
  },
  {
    id: 'lemon',
    title: 'Lemon',
    artist: '米津玄師',
    language: 'japanese',
    genres: ['pop'],
    moods: ['low', 'lonely', 'unclear'],
    energy: 0.52,
    reason: '苦涩与明亮交错，让无法复原的记忆仍保留被珍惜的形状。',
    accent: ['#9c8c65', '#2e3740'],
  },
  {
    id: 'plastic-love',
    title: 'Plastic Love',
    artist: '竹内まりや',
    language: 'japanese',
    genres: ['rnb', 'pop', 'classic'],
    moods: ['happy', 'calm', 'lonely'],
    energy: 0.72,
    reason: '都市感的律动轻盈又疏离，适合让情绪在夜色里自在游走。',
    accent: ['#aa7685', '#283445'],
  },
  {
    id: 'stay-with-me-miki',
    title: '真夜中のドア〜Stay With Me',
    artist: '松原みき',
    language: 'japanese',
    genres: ['rnb', 'pop', 'classic'],
    moods: ['calm', 'lonely', 'happy'],
    energy: 0.7,
    reason: '复古而流畅的律动让夜晚变得柔软，也给想念留下一点光泽。',
    accent: ['#9f7b88', '#2d3546'],
  },
  {
    id: 'nandemonaiya',
    title: 'なんでもないや',
    artist: 'RADWIMPS',
    language: 'japanese',
    genres: ['rock', 'pop'],
    moods: ['low', 'lonely', 'unclear'],
    energy: 0.46,
    reason: '克制的开场逐渐靠近心事，让那些说不出口的话拥有自己的回声。',
    accent: ['#7f94a5', '#313549'],
  },
  {
    id: 'bling-bang-bang-born',
    title: 'Bling-Bang-Bang-Born',
    artist: 'Creepy Nuts',
    language: 'japanese',
    genres: ['rap', 'pop'],
    moods: ['happy', 'angry', 'tired'],
    energy: 0.96,
    reason: '快速而富有弹性的节奏立即提亮状态，让积压的能量痛快释放。',
    accent: ['#b19451', '#302b3e'],
  },
  {
    id: 'ditto',
    title: 'Ditto',
    artist: 'NewJeans',
    language: 'korean',
    genres: ['pop', 'rnb'],
    moods: ['lonely', 'calm', 'low'],
    energy: 0.48,
    reason: '轻柔的节拍像冬日玻璃上的雾，让想念保持朦胧而不至于沉重。',
    accent: ['#8fa0a8', '#2f3745'],
  },
  {
    id: 'love-wins-all',
    title: 'Love wins all',
    artist: 'IU',
    language: 'korean',
    genres: ['pop'],
    moods: ['low', 'lonely', 'calm'],
    energy: 0.4,
    reason: '温柔而辽阔的声音为脆弱留出余地，也让陪伴显得更坚定。',
    accent: ['#9d8893', '#303a4c'],
  },
  {
    id: 'two-hundred-percent',
    title: '200%',
    artist: 'AKMU',
    language: 'korean',
    genres: ['pop', 'folk'],
    moods: ['happy', 'calm'],
    energy: 0.78,
    reason: '清新的和声与轻快节奏不费力地靠近，让明亮多停留一会儿。',
    accent: ['#8eb69c', '#354858'],
  },
  {
    id: 'instagram-dean',
    title: 'instagram',
    artist: 'DEAN',
    language: 'korean',
    genres: ['rnb'],
    moods: ['lonely', 'unclear', 'tired'],
    energy: 0.36,
    reason: '松弛而疏离的声线适合深夜独处，让无处安放的思绪慢慢沉下来。',
    accent: ['#817c82', '#252d38'],
  },
  {
    id: 'any-song-zico',
    title: 'Any Song',
    artist: 'ZICO',
    language: 'korean',
    genres: ['rap', 'pop'],
    moods: ['happy', 'tired', 'unclear'],
    energy: 0.82,
    reason: '随性的律动先让身体松开一点，不要求此刻一定拥有明确答案。',
    accent: ['#aa8b60', '#2d3740'],
  },
  {
    id: 'eres',
    title: 'Eres',
    artist: 'Café Tacvba',
    language: 'other',
    genres: ['rock', 'pop'],
    moods: ['happy', 'calm', 'lonely'],
    energy: 0.58,
    reason: '真挚而明亮的旋律让喜欢变得简单，也给孤单带来柔和回应。',
    accent: ['#ad8367', '#35413d'],
  },
  {
    id: 'gracias-a-la-vida',
    title: 'Gracias a la Vida',
    artist: 'Mercedes Sosa',
    language: 'other',
    genres: ['folk', 'classic'],
    moods: ['calm', 'tired', 'happy'],
    energy: 0.38,
    reason: '厚实而从容的歌声回望生命，让疲惫之中仍能看见值得珍惜的部分。',
    accent: ['#9c785b', '#343c38'],
  },
  {
    id: 'volare',
    title: 'Nel blu, dipinto di blu (Volare)',
    artist: 'Domenico Modugno',
    language: 'other',
    genres: ['classic', 'pop'],
    moods: ['happy', 'calm'],
    energy: 0.78,
    reason: '开阔的旋律像迎面而来的风，让快乐自然舒展而不需要理由。',
    accent: ['#6799ad', '#33435a'],
  },
  {
    id: 'ninety-nine-luftballons',
    title: '99 Luftballons',
    artist: 'Nena',
    language: 'other',
    genres: ['rock', 'pop', 'classic'],
    moods: ['angry', 'happy', 'unclear'],
    energy: 0.88,
    reason: '明快外表下藏着锋利表达，让复杂情绪可以一边跳动一边思考。',
    accent: ['#ba7968', '#323344'],
  },
  {
    id: 'aguas-de-marco',
    title: 'Águas de Março',
    artist: 'Elis Regina & Tom Jobim',
    language: 'other',
    genres: ['blues', 'classic', 'light'],
    moods: ['happy', 'calm', 'tired'],
    energy: 0.62,
    reason: '像流水般往复的对唱轻盈又松弛，把日常碎片重新拼成生动节奏。',
    accent: ['#8ea27b', '#39453e'],
  },
]

export const songs: Song[] = [...curatedSongs, ...expandedSongs]

validateCatalog(songs)

export const labels = {
  moods: Object.fromEntries(moodOptions.map((item) => [item.id, item.label])) as Record<MoodId, string>,
  languages: Object.fromEntries(languageOptions.map((item) => [item.id, item.label])) as Record<LanguageId, string>,
  genres: Object.fromEntries(genreOptions.map((item) => [item.id, item.label])) as Record<GenreId, string>,
}
